- name: install and run nginx
  hosts: practice
  become: true 
  tasks:
  - name: install nginx 
    ansible.builtin.dnf:  
      name: nginx 
      state: present 
  
  - name: run nginx 
    ansible.builtin.service:
      name: nginx 
      state: started 
      enabled: true 
  
  # - name: stop nginx 
  #   ansible.builtin.service:
  #     name: nginx 
  #     state: stopped 
  #     enabled: false  

  # - name: remove/uninstall nginx 
  #   ansible.builtin.dnf:
  #     name: nginx
  #     state: absent 