- name: variables from task level 
  hosts: practice
  become: true 
  vars:
      package_name: "nginx"
  tasks:
  - name: "Install {{package_name}}"
    vars:
      package_name: "nginx"
    ansible.builtin.dnf:
      name: "{{package_name}}"
      state: present

  - name: "Run {{package_name}}"
    # vars:
    #   package_name: "nginx"
    ansible.builtin.service:
      name: "{{package_name}}"
      state: started 
      enabled: true 