- name: variables from inventory file level 
  hosts: practice
  become: true 
  tasks:
  - name: "Install {{package_name}}"
    ansible.builtin.dnf:
      name: "{{package_name}}"
      state: present

  - name: "Run {{package_name}}"
    ansible.builtin.service:
      name: "{{package_name}}"
      state: started 
      enabled: true 

#Run : ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 08-variables-from-inventory-file.yaml

# [practice:vars]                             #or all by default in place of practice
# package_name= "nginx"
#mention the above line in inventory file  --> practice -- host/servername or put all for [all:vars] servers if variables needed 