- name: variables from group_vars-level
  hosts: practice
  become: true 
  tasks:
  - name: "Install {{package_name}}"
    ansible.builtin.dnf:
      name: "{{package_name}}"
      state: present

  - name: "Run {{package_name}}"
    ansible.builtin.service:
      name: "{{package_name}}"
      state: started 
      enabled: true 