[practice]
54.197.213.92

#---------------------------- from here data for host variables-----------------

; [practice]                  #for host_vars
; server1 ansible_host=54.197.213.92
; server2 ansible_host=32.197.125.140

#server1 --> file name given in host_vars folder without extension if u give file name as web.yaml give here as web in place of server 1 


#---------------------------- from here data for group variables-----------------

; [nginx_servers]          #for group vars
; server1 ansible_host=54.197.213.92
; server3 ansible_host=32.197.125.140

; [apache_servers]
; server2 ansible_host=54.198.138.190

;  #just target identifiers server2 and server1 etcc..we can give any name 

; [practice:children]              
; nginx_servers
; apache_servers

#in group vars we dont need to give same file name to each server ip we can give group name that matches the file name automatically 
#it means Ansible automatically maps the filenames to the group names for you behind the scenes

#---------------------------- untill this -----------------

[practice:vars]                             #or all by default in place of practice
package_name="nginx"

ansible_user="ec2-user"
ansible_password="DevOps321"
