; [practice]
; 54.197.213.92
; 52.203.141.221



[practice]                  #for host_vars
server1 ansible_host=54.197.213.92
server2 ansible_host=52.203.141.221


#server1 --> file name given in host_vars folder without extension if u give file name as web.yaml give here as web in place of server 1 

[practice:vars]                             #or all by default in place of practice
package_name="nginx"

ansible_user="ec2-user"
ansible_password="DevOps321"
