[mongodb]
mongodb.devopswitharun.online
[redis]
redis.devopswitharun.online
[mysql]
mysql.devopswitharun.online
[rabbitmq]
rabbitmq.devopswitharun.online

[catalogue]
catalogue.devopswitharun.online
[user]
user.devopswitharun.online
[cart]
cart.devopswitharun.online

[shipping]
shipping.devopswitharun.online
[payment]
payment.devopswitharun.online
[web]
web.devopswitharun.online

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321