[web]
<ip>

[web:vars]      #for this file 08-variables-from-inventory-file.yaml
package_name= "nginx"
state= "present"
course= "DevOps"
name= "Arun"

name="name From inventory file level"
course="course From inventory file level"